export const PUBLICATION_NAMES = [
  '850 Business Magazine',
  'Advances - Tampa General',
  'Art & Culture',
  'At the Beach',
  'Aventura',
  'Club Braman',
  'Community Foundation',
  'Cultural Arts Alliance',
  'Emerald Coast Magazine',
  'Fifth Ave S.',
  'Florida Design Mag',
  'Florida Design Miami',
  'Florida Design Naples',
  'Florida Design Sarasota',
  'Florida Design Sourcebook',
  'General Magazines (Mixed Pallets)',
  'Hilton Sandestin Footprints',
  'Jupiter Mag',
  'NABOR',
  'Naples 100',
  'Naples Charity Register',
  'Naples Illustrated',
  'Naples on the Gulf',
  'Naples Yacht Club - Waypoints',
  'NW FL Weddings',
  'Palm Beach Charity Register',
  'Palm Beach Illustrated',
  'Panama City Beach Visitors Guide',
  'PB Relocation',
  'Pinnacle',
  'Sandestin Living',
  'Stuart',
  'Studer Building Blocks',
  'SW FL Relocation',
  'Tallahassee Magazine',
  'Tallahassee Newcomers Guide',
  'Tallahassee Physicians & Medical Resource Guide',
  'Vero Beach Handbook',
  'Vero Beach Magazine',
  'Vero Beach Time & Treasure',
  'Visit Tallahassee',
  'Visit Tallahassee Meeting Planner',
  'Watersound Lifestyle',
  'Woods Trust',
];
